class CardSerializer
  include JSONAPI::Serializer
  attributes :name,
             :card_code,
             :description,
             :description_raw,
             :levelup_description,
             :levelup_description_raw,
             :flavor_text,
             :artist_name,
             :attack,
             :cost,
             :health,
             :spell_speed,
             :rarity,
             :supertype,
             :card_type,
             :collectible,
             :set,
             :associated_card_refs,
             :regions,
             :region_refs,
             :keywords,
             :keyword_refs,
             :formats,
             :format_refs,
             :assets
end
